In [104]:
import json
from sklearn.model_selection import train_test_split
import pandas as pd
from IPython.core.display import HTML, display
from torchtext.data.utils import get_tokenizer
from torch.utils.data import DataLoader
from torchtext.vocab import Vocab
import torch
from torch import nn
from collections import Counter

/var/folders/6k/hf1g4x5515d_37kbfk7wk_j00000gn/T/ipykernel_90577/286711138.py:4: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import HTML, display


In [105]:
# Path to the All_Beauty reviews file you downloaded
reviews_file_path = 'amazon_cells_labelled.csv'
SEED = 0

In [106]:
# Load the csv file
df = pd.read_csv(reviews_file_path, header=0, names=['text', 'rating'])
df

text  rating
0    So there is no way for me to plug it in here i...       0
1                          Good case, Excellent value.       1
2                               Great for the jawbone.       1
3    Tied to charger for conversations lasting more...       0
4                                    The mic is great.       1
..                                                 ...     ...
995  The screen does get smudged easily because it ...       0
996  What a piece of junk.. I lose more calls on th...       0
997                       Item Does Not Match Picture.       0
998  The only thing that disappoint me is the infra...       0
999  You can not answer calls with the unit, never ...       0

[1000 rows x 2 columns]

In [107]:
texts = df['text'].tolist()
ratings = df['rating'].tolist()

In [108]:
# get indices where number of words is > 5 and number of words is < 100
# indices = [i for i, text in enumerate(texts) if 5 < len(text.split()) < 100]
# texts = [texts[i] for i in indices]
# ratings = [int(ratings[i]) for i in indices]

In [109]:
# Convert ratings to binary sentiment (1 for positive, 0 for negative)
# sentiments = [1 if rating >= 4 else 0 for rating in ratings]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(texts, ratings, test_size=0.2, random_state=SEED)


In [110]:
# pkl the train and test data
train_df = pd.DataFrame({'text': X_train, 'sentiment': y_train})
test_df = pd.DataFrame({'text': X_test, 'sentiment': y_test})
train_df.to_pickle('amazon_1000-train.pkl')
test_df.to_pickle('amazon_1000-test.pkl')

In [111]:
len(X_train), len(X_test)

(800, 200)

In [112]:
tokenizer = get_tokenizer('basic_english')
word_counter = Counter()
for (line, label) in zip(X_train, y_train):
    print(line)
    word_counter.update(tokenizer(line))
voc = Vocab(word_counter, min_freq=10)

print('Vocabulary size:', len(voc))

num_class = len(set(y_train))
print('Num of classes:', num_class)

i would advise to not purchase this item it never worked very well.
The bose noise cancelling is amazing, which is very important for a NYC commuter.
The reception is excellent!
Not enough volume.
Gets a signal when other Verizon phones won't.
Steer clear of this product and go with the genuine Palm replacementr pens, which come in a three-pack.
Battery has no life.
I am very impressed with the job that Motorola did on the sturdiness of this phone.
The phone is sturdy and waterproof.
A lot of websites have been rating this a very good phone and so do I.
Great product, fast shipping!.
I like design and look of Jabra behing the ear headsets and 5020 is pretty comfortible to wear 24 hours a day without pain in the ear.
Poor Talk Time Performance.
This product is very High quality Chinese CRAP!!!!!!
It was quite comfortable in the ear.
Lasted one day and then blew up.
And I just love the colors!
I've bought $5 wired headphones that sound better than these.
It has a great camera thats 2MP, 

In [113]:
y_train

[0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,


In [114]:
class EmbeddingBagModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_class):
        super().__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim)
        self.linear = nn.Linear(embed_dim, num_class)

    def forward(self, inputs, offsets):
        embedded = self.embedding(inputs, offsets)
        return self.linear(embedded)

In [115]:
BATCH_SIZE = 64

def collate_batch(batch, tokenizer, voc):
    labels = torch.tensor([label for _, label in batch]) 
    text_list = [tokenizer(line) for line, _ in batch]
    
    # flatten tokens across the whole batch
    text = torch.tensor([voc[t] for tokens in text_list for t in tokens])
    tokenized_list = [torch.tensor([voc[t] for t in tokens]) for tokens in text_list]
    # the offset of each example
    offsets = torch.tensor(
        [0] + [len(tokens) for tokens in text_list][:-1]
    ).cumsum(dim=0)

    return labels, text, offsets, tokenized_list

train_loader = DataLoader(list(zip(X_train, y_train)), batch_size=BATCH_SIZE, shuffle=True, collate_fn=lambda batch: collate_batch(batch, tokenizer, voc))
test_loader = DataLoader(list(zip(X_test, y_test)), batch_size=BATCH_SIZE, shuffle=False, collate_fn=lambda batch: collate_batch(batch, tokenizer, voc))

In [116]:
EPOCHS = 500
EMB_SIZE = 32
CHECKPOINT = './models/embedding_bag_amazon_1000'
USE_PRETRAINED = False  # change to False if you want to retrain your own model

def train_model(train_loader, val_loader):
    model = EmbeddingBagModel(len(voc), EMB_SIZE, num_class)
    
    loss = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters())
    best_acc = 0
    for epoch in range(1, EPOCHS + 1):      
        # training
        model.train()
        total_acc, total_count = 0, 0
        
        for idx, (label, text, offsets, _) in enumerate(train_loader):
            optimizer.zero_grad()
            predited_label = model(text, offsets)
            loss(predited_label, label).backward()
            optimizer.step()
            total_acc += (predited_label.argmax(1) == label).sum().item()
            total_count += label.size(0)

            if (idx + 1) % 500 == 0:
                print('epoch {:3d} | {:5d}/{:5d} batches | accuracy {:8.3f}'.format(
                    epoch, idx + 1, len(train_loader), total_acc / total_count
                ))
                total_acc, total_count = 0, 0       
        
        # evaluation
        model.eval()
        total_acc, total_count = 0, 0

        with torch.no_grad():
            for label, text, offsets, _ in val_loader:
                predited_label = model(text, offsets)
                total_acc += (predited_label.argmax(1) == label).sum().item()
                total_count += label.size(0)

        # print('-' * 59)
        acc = total_acc / total_count
        print('end of epoch {:3d} | valid accuracy {:8.3f} '.format(epoch, acc))
        # print('-' * 59)
        if total_acc/total_count > best_acc:
            best_acc = acc
            print('best_acc', best_acc)
            # torch.save(model, CHECKPOINT+'_epoch'+str(epoch)+'.pt')
    return model
        
eb_model = torch.load(CHECKPOINT) if USE_PRETRAINED else train_model(train_loader, test_loader)

end of epoch   1 | valid accuracy    0.550 
best_acc 0.55
end of epoch   2 | valid accuracy    0.560 
best_acc 0.56
end of epoch   3 | valid accuracy    0.600 
best_acc 0.6
end of epoch   4 | valid accuracy    0.600 
end of epoch   5 | valid accuracy    0.630 
best_acc 0.63
end of epoch   6 | valid accuracy    0.635 
best_acc 0.635
end of epoch   7 | valid accuracy    0.645 
best_acc 0.645
end of epoch   8 | valid accuracy    0.660 
best_acc 0.66
end of epoch   9 | valid accuracy    0.665 
best_acc 0.665
end of epoch  10 | valid accuracy    0.645 
end of epoch  11 | valid accuracy    0.655 
end of epoch  12 | valid accuracy    0.665 
end of epoch  13 | valid accuracy    0.675 
best_acc 0.675
end of epoch  14 | valid accuracy    0.680 
best_acc 0.68
end of epoch  15 | valid accuracy    0.685 
best_acc 0.685
end of epoch  16 | valid accuracy    0.670 
end of epoch  17 | valid accuracy    0.675 
end of epoch  18 | valid accuracy    0.680 
end of epoch  19 | valid accuracy    0.685 
end of

In [136]:
from captum.attr import Lime, LimeBase
from captum._utils.models.linear_model import SkLearnLinearRegression, SkLearnLasso

import torch.nn.functional as F

In [131]:
# remove the batch dimension for the embedding-bag model
def forward_func(text, offsets):
    return eb_model(text.squeeze(0), offsets)

# encode text indices into latent representations & calculate cosine similarity
def exp_embedding_cosine_distance(original_inp, perturbed_inp, _, **kwargs):
    original_emb = eb_model.embedding(original_inp, None)
    perturbed_emb = eb_model.embedding(perturbed_inp, None)
    distance = 1 - F.cosine_similarity(original_emb, perturbed_emb, dim=1)
    return torch.exp(-1 * (distance ** 2) / 2)

# binary vector where each word is selected independently and uniformly at random
def bernoulli_perturb(text, **kwargs):
    probs = torch.ones_like(text) * 0.5
    return torch.bernoulli(probs).long()

# remove absenst token based on the intepretable representation sample
def interp_to_input(interp_sample, original_input, **kwargs):
    return original_input[interp_sample.bool()].view(original_input.size(0), -1)

lasso_lime_base = LimeBase(
    forward_func, 
    interpretable_model=SkLearnLasso(alpha=0.08),
    similarity_func=exp_embedding_cosine_distance,
    perturb_func=bernoulli_perturb,
    perturb_interpretable_space=True,
    from_interp_rep_transform=interp_to_input,
    to_interp_rep_transform=None
)

In [132]:
def show_text_attr(attrs):
    rgb = lambda x: '255,0,0' if x < 0 else '0,255,0'
    alpha = lambda x: abs(x) ** 0.5
    token_marks = [
        f'<mark style="background-color:rgba({rgb(attr)},{alpha(attr)})">{token}</mark>'
        for token, attr in zip(tokenizer(test_line), attrs.tolist())
    ]
    
    display(HTML('<p>' + ' '.join(token_marks) + '</p>'))

In [172]:
test_label = 1 
test_line = ('I love it not very much')

test_labels, test_text, test_offsets, _ = collate_batch([(test_line, test_label)], tokenizer, voc)

probs = F.softmax(eb_model(test_text, test_offsets), dim=1).squeeze(0)
print('Prediction probability:', round(probs[test_labels[0]].item(), 4))

Prediction probability: 0.8483


In [173]:
test_text, test_labels, probs, test_offsets

(tensor([ 4, 90,  6, 18, 20,  0]),
 tensor([1]),
 tensor([0.1517, 0.8483], grad_fn=<SqueezeBackward1>),
 tensor([0]))

In [161]:
attrs = lasso_lime_base.attribute( test_text.unsqueeze(0), target=test_labels, additional_forward_args=(test_offsets,), n_samples=16, show_progress=True).squeeze(0)

print('Attribution range:', attrs.min().item(), 'to', attrs.max().item())

Lime Base attribution:   0%|          | 0/16 [00:00<?, ?it/s]

RuntimeError: step must be nonzero

In [158]:
# positive
show_text_attr(attrs)

In [60]:
# positive
attrs = lasso_lime_base.attribute(
    test_text.unsqueeze(0), # add batch dimension for Captum
    target=test_labels,
    additional_forward_args=(test_offsets,),
    n_samples=5000,
    show_progress=True
).squeeze(0)

print('Attribution range:', attrs.min().item(), 'to', attrs.max().item())

Lime Base attribution:   0%|          | 0/5000 [00:00<?, ?it/s]

Attribution range: -1.5195974111557007 to 1.7107371091842651
