In [1]:
import json
from sklearn.model_selection import train_test_split
import pandas as pd
from IPython.core.display import HTML, display
from torchtext.data.utils import get_tokenizer
from torch.utils.data import DataLoader
from torchtext.vocab import Vocab
import torch
from torch import nn
from collections import Counter

/var/folders/6k/hf1g4x5515d_37kbfk7wk_j00000gn/T/ipykernel_11748/286711138.py:4: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import HTML, display


In [2]:
# Path to the All_Beauty reviews file you downloaded
reviews_file_path = 'yelp_labelled.csv'
SEED = 0

In [3]:
# Load the csv file
df = pd.read_csv(reviews_file_path, header=0, names=['text', 'rating'])
df

text  rating
0                             Wow... Loved this place.       1
1                                   Crust is not good.       0
2            Not tasty and the texture was just nasty.       0
3    Stopped by during the late May bank holiday of...       1
4    The selection on the menu was great and so wer...       1
..                                                 ...     ...
995  I think food should have flavor and texture an...       0
996                           Appetite instantly gone.       0
997  Overall I was not impressed and would not go b...       0
998  The whole experience was underwhelming, and I ...       0
999  Then, as if I hadn't wasted enough of my life ...       0

[1000 rows x 2 columns]

In [4]:
texts = df['text'].tolist()
ratings = df['rating'].tolist()

In [5]:
# get indices where number of words is > 5 and number of words is < 100
# indices = [i for i, text in enumerate(texts) if 5 < len(text.split()) < 100]
# texts = [texts[i] for i in indices]
# ratings = [int(ratings[i]) for i in indices]

In [6]:
# Convert ratings to binary sentiment (1 for positive, 0 for negative)
# sentiments = [1 if rating >= 4 else 0 for rating in ratings]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(texts, ratings, test_size=0.2, random_state=SEED)


In [9]:
# pkl the train and test data
train_df = pd.DataFrame({'text': X_train, 'sentiment': y_train})
test_df = pd.DataFrame({'text': X_test, 'sentiment': y_test})
train_df.to_pickle('yelp-train.pkl')
test_df.to_pickle('yelp-test.pkl')

In [8]:
len(X_train), len(X_test)

(800, 200)

In [10]:
tokenizer = get_tokenizer('basic_english')
word_counter = Counter()
for (line, label) in zip(X_train, y_train):
    print(line)
    word_counter.update(tokenizer(line))
voc = Vocab(word_counter, min_freq=10)

print('Vocabulary size:', len(voc))

num_class = len(set(y_train))
print('Num of classes:', num_class)

The decor is nice, and the piano music soundtrack is pleasant.
I also had to taste my Mom's multi-grain pumpkin pancakes with pecan butter and they were amazing, fluffy, and delicious!
We had fantastic service, and were pleased by the atmosphere.
I kept looking at the time and it had soon become 35 minutes, yet still no food.
The seasonal fruit was fresh white peach puree.
I had the chicken Pho and it tasted very bland.
I love this place.
it was a drive to get there.
Anyway, I do not think i will go back there.
It was equally awful.
Nice, spicy and tender.
The chicken I got was definitely reheated and was only ok, the wedges were cold and soggy.
Poor service, the waiter made me feel like I was stupid every time he came to the table.
If you stay in Vegas you must get breakfast here at least once.
I want to first say our server was great and we had perfect service.
A lady at the table next to us found a live green caterpillar In her salad.
this place is good.
Some highlights : Great qual

In [11]:
y_train

[1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,


In [12]:
class EmbeddingBagModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_class):
        super().__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim)
        self.linear = nn.Linear(embed_dim, num_class)

    def forward(self, inputs, offsets):
        embedded = self.embedding(inputs, offsets)
        return self.linear(embedded)

In [13]:
BATCH_SIZE = 64

def collate_batch(batch, tokenizer, voc):
    labels = torch.tensor([label for _, label in batch]) 
    text_list = [tokenizer(line) for line, _ in batch]
    
    # flatten tokens across the whole batch
    text = torch.tensor([voc[t] for tokens in text_list for t in tokens])
    tokenized_list = [torch.tensor([voc[t] for t in tokens]) for tokens in text_list]
    # the offset of each example
    offsets = torch.tensor(
        [0] + [len(tokens) for tokens in text_list][:-1]
    ).cumsum(dim=0)

    return labels, text, offsets, tokenized_list

train_loader = DataLoader(list(zip(X_train, y_train)), batch_size=BATCH_SIZE, shuffle=True, collate_fn=lambda batch: collate_batch(batch, tokenizer, voc))
test_loader = DataLoader(list(zip(X_test, y_test)), batch_size=BATCH_SIZE, shuffle=False, collate_fn=lambda batch: collate_batch(batch, tokenizer, voc))

In [15]:
EPOCHS = 500
EMB_SIZE = 32
CHECKPOINT = './models/embedding_bag_amazon_1000'
USE_PRETRAINED = False  # change to False if you want to retrain your own model

def train_model(train_loader, val_loader):
    model = EmbeddingBagModel(len(voc), EMB_SIZE, num_class)
    
    loss = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters())
    best_acc = 0
    for epoch in range(1, EPOCHS + 1):      
        # training
        model.train()
        total_acc, total_count = 0, 0
        
        for idx, (label, text, offsets, _) in enumerate(train_loader):
            optimizer.zero_grad()
            predited_label = model(text, offsets)
            loss(predited_label, label).backward()
            optimizer.step()
            total_acc += (predited_label.argmax(1) == label).sum().item()
            total_count += label.size(0)

            if (idx + 1) % 500 == 0:
                print('epoch {:3d} | {:5d}/{:5d} batches | accuracy {:8.3f}'.format(
                    epoch, idx + 1, len(train_loader), total_acc / total_count
                ))
                total_acc, total_count = 0, 0       
        
        # evaluation
        model.eval()
        total_acc, total_count = 0, 0

        with torch.no_grad():
            for label, text, offsets, _ in val_loader:
                predited_label = model(text, offsets)
                total_acc += (predited_label.argmax(1) == label).sum().item()
                total_count += label.size(0)

        # print('-' * 59)
        acc = total_acc / total_count
        print('end of epoch {:3d} | valid accuracy {:8.3f} '.format(epoch, acc))
        # print('-' * 59)
        if total_acc/total_count > best_acc:
            best_acc = acc
            print('best_acc', best_acc)
            torch.save(model, CHECKPOINT+'_epoch'+str(epoch)+'.pt')
    return model
        
eb_model = torch.load(CHECKPOINT) if USE_PRETRAINED else train_model(train_loader, test_loader)

end of epoch   1 | valid accuracy    0.460 
best_acc 0.46
end of epoch   2 | valid accuracy    0.470 
best_acc 0.47
end of epoch   3 | valid accuracy    0.515 
best_acc 0.515
end of epoch   4 | valid accuracy    0.560 
best_acc 0.56
end of epoch   5 | valid accuracy    0.565 
best_acc 0.565
end of epoch   6 | valid accuracy    0.595 
best_acc 0.595
end of epoch   7 | valid accuracy    0.610 
best_acc 0.61
end of epoch   8 | valid accuracy    0.600 
end of epoch   9 | valid accuracy    0.640 
best_acc 0.64
end of epoch  10 | valid accuracy    0.645 
best_acc 0.645
end of epoch  11 | valid accuracy    0.635 
end of epoch  12 | valid accuracy    0.650 
best_acc 0.65
end of epoch  13 | valid accuracy    0.670 
best_acc 0.67
end of epoch  14 | valid accuracy    0.670 
end of epoch  15 | valid accuracy    0.680 
best_acc 0.68
end of epoch  16 | valid accuracy    0.680 
end of epoch  17 | valid accuracy    0.680 
end of epoch  18 | valid accuracy    0.695 
best_acc 0.695
end of epoch  19 | va

KeyboardInterrupt: 

In [51]:
from torch.nn import functional as F
test_label = 1 
test_line = ('I sort of like this product, its really not my favorite, but it really isnt the best. could be way better.')

test_labels, test_text, test_offsets, _ = collate_batch([(test_line, test_label)])

probs = F.softmax(eb_model(test_text, test_offsets), dim=1).squeeze(0)
print('Prediction probability:', round(probs[test_labels[0]].item(), 4))

Prediction probability: 0.311


In [52]:
probs

tensor([0.6890, 0.3110], grad_fn=<SqueezeBackward1>)

In [53]:
from captum.attr import Lime, LimeBase
from captum._utils.models.linear_model import SkLearnLinearRegression, SkLearnLasso

In [54]:
# remove the batch dimension for the embedding-bag model
def forward_func(text, offsets):
    return eb_model(text.squeeze(0), offsets)

# encode text indices into latent representations & calculate cosine similarity
def exp_embedding_cosine_distance(original_inp, perturbed_inp, _, **kwargs):
    original_emb = eb_model.embedding(original_inp, None)
    perturbed_emb = eb_model.embedding(perturbed_inp, None)
    distance = 1 - F.cosine_similarity(original_emb, perturbed_emb, dim=1)
    return torch.exp(-1 * (distance ** 2) / 2)

# binary vector where each word is selected independently and uniformly at random
def bernoulli_perturb(text, **kwargs):
    probs = torch.ones_like(text) * 0.5
    return torch.bernoulli(probs).long()

# remove absenst token based on the intepretable representation sample
def interp_to_input(interp_sample, original_input, **kwargs):
    return original_input[interp_sample.bool()].view(original_input.size(0), -1)

lasso_lime_base = LimeBase(
    forward_func, 
    interpretable_model=SkLearnLasso(alpha=0.08),
    similarity_func=exp_embedding_cosine_distance,
    perturb_func=bernoulli_perturb,
    perturb_interpretable_space=True,
    from_interp_rep_transform=interp_to_input,
    to_interp_rep_transform=None
)

In [55]:
test_text, test_labels

(tensor([  4,   0,  18,  50,  11,  43,   7,  90,  64,  17,  13,   0,   7,  31,
           6,  64,   0,   3,  63,   2, 108,  44,   0,  87,   2]),
 tensor([1]))

In [58]:
attrs = lasso_lime_base.attribute(
    test_text.unsqueeze(0), # add batch dimension for Captum
    target=test_labels,
    additional_forward_args=(test_offsets,),
    n_samples=16,
    show_progress=True
).squeeze(0)

print('Attribution range:', attrs.min().item(), 'to', attrs.max().item())

Lime Base attribution:   0%|          | 0/16 [00:00<?, ?it/s]

Attribution range: -0.8828542232513428 to 1.0538634061813354


In [59]:
def show_text_attr(attrs):
    rgb = lambda x: '255,0,0' if x < 0 else '0,255,0'
    alpha = lambda x: abs(x) ** 0.5
    token_marks = [
        f'<mark style="background-color:rgba({rgb(attr)},{alpha(attr)})">{token}</mark>'
        for token, attr in zip(tokenizer(test_line), attrs.tolist())
    ]
    
    display(HTML('<p>' + ' '.join(token_marks) + '</p>'))

In [60]:
# positive
attrs = lasso_lime_base.attribute(
    test_text.unsqueeze(0), # add batch dimension for Captum
    target=test_labels,
    additional_forward_args=(test_offsets,),
    n_samples=5000,
    show_progress=True
).squeeze(0)

print('Attribution range:', attrs.min().item(), 'to', attrs.max().item())

Lime Base attribution:   0%|          | 0/5000 [00:00<?, ?it/s]

Attribution range: -1.5195974111557007 to 1.7107371091842651


In [61]:
# positive
show_text_attr(attrs)