In [27]:
import json
from sklearn.model_selection import train_test_split
import pandas as pd
from IPython.core.display import HTML, display
from torchtext.data.utils import get_tokenizer
from torch.utils.data import DataLoader
from torchtext.vocab import Vocab
import torch
from torch import nn
from collections import Counter

/var/folders/6k/hf1g4x5515d_37kbfk7wk_j00000gn/T/ipykernel_8821/286711138.py:4: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import HTML, display


In [31]:
# Path to the All_Beauty reviews file you downloaded
reviews_file_path = 'imdb_labelled.csv'
SEED = 0

In [32]:
# Load the csv file
df = pd.read_csv(reviews_file_path, header=0, names=['text', 'rating'])
df

text  rating
0    A very, very, very slow-moving, aimless movie ...       0
1    Not sure who was more lost - the flat characte...       0
2    Attempting artiness with black & white and cle...       0
3         Very little music or anything to speak of.         0
4    The best scene in the movie was when Gerardo i...       1
..                                                 ...     ...
995  I just got bored watching Jessice Lange take h...       0
996  Unfortunately, any virtue in this film's produ...       0
997                   In a word, it is embarrassing.         0
998                               Exceptionally bad!         0
999  All in all its an insult to one's intelligence...       0

[1000 rows x 2 columns]

In [33]:
 # find the row with the longest text
max_len = 0
max_len_idx = 0
max_sentence = ''
for i, row in df.iterrows():
    if len(row['text']) > max_len:
        max_len = len(row['text'])
        max_len_idx = i
        max_sentence = row['text']
print(max_len, max_len_idx, max_sentence)

479 620 This is a masterful piece of film-making, with many themes simmering and occasionally boiling over in this warts and all study of the poet's bohemian, self-indulgent wartime years that span the aerial bombardments of London and the outward tranquillity of a Welsh coastal retreat - the borderlines between friendship, lust and love, dedication to art and experience versus practical concerns, jealousy, rivalry, cowardice and egotism versus heroism and self-sacrifice and more.  


In [34]:
texts = df['text'].tolist()
ratings = df['rating'].tolist()

In [35]:
# get indices where number of words is > 5 and number of words is < 100
# indices = [i for i, text in enumerate(texts) if 5 < len(text.split()) < 100]
# texts = [texts[i] for i in indices]
# ratings = [int(ratings[i]) for i in indices]

In [36]:
# Convert ratings to binary sentiment (1 for positive, 0 for negative)
# sentiments = [1 if rating >= 4 else 0 for rating in ratings]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(texts, ratings, test_size=0.2, random_state=SEED)


In [37]:
# pkl the train and test data
train_df = pd.DataFrame({'text': X_train, 'sentiment': y_train})
test_df = pd.DataFrame({'text': X_test, 'sentiment': y_test})
train_df.to_pickle('imdb-train.pkl')
test_df.to_pickle('imdb-test.pkl')

In [38]:
len(X_train), len(y_train), len(X_test), len(y_test)

(800, 800, 200, 200)

In [39]:
tokenizer = get_tokenizer('basic_english')
word_counter = Counter()
for (line, label) in zip(X_train, y_train):
    print(line)
    word_counter.update(tokenizer(line))
voc = Vocab(word_counter, min_freq=10)

print('Vocabulary size:', len(voc))

num_class = len(set(y_train))
print('Num of classes:', num_class)

10 out of 10 stars.  
The entire audience applauded at the conclusion of the film.  
To call this movie a drama is ridiculous!  	
It is a very well acted and done TV Movie.  
You will leave the theater wanting to go out and dance under the stars.  
This is a masterful piece of film-making, with many themes simmering and occasionally boiling over in this warts and all study of the poet's bohemian, self-indulgent wartime years that span the aerial bombardments of London and the outward tranquillity of a Welsh coastal retreat - the borderlines between friendship, lust and love, dedication to art and experience versus practical concerns, jealousy, rivalry, cowardice and egotism versus heroism and self-sacrifice and more.  
You share General Loewenhielm's exquisite joy in his partaking of the Cailles en Sarcophage even though you are just watching a movie - but you do wish for just a small sample to savor.  
I could not understand, what kind of idiot would produce this mess in the first pla

In [13]:
y_train

[0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,


In [14]:
class EmbeddingBagModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_class):
        super().__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim)
        self.linear = nn.Linear(embed_dim, num_class)

    def forward(self, inputs, offsets):
        embedded = self.embedding(inputs, offsets)
        return self.linear(embedded)

In [12]:
BATCH_SIZE = 64

def collate_batch(batch, tokenizer, voc):
    labels = torch.tensor([label for _, label in batch]) 
    text_list = [tokenizer(line) for line, _ in batch]
    
    # flatten tokens across the whole batch
    text = torch.tensor([voc[t] for tokens in text_list for t in tokens])
    tokenized_list = [torch.tensor([voc[t] for t in tokens]) for tokens in text_list]
    # the offset of each example
    offsets = torch.tensor(
        [0] + [len(tokens) for tokens in text_list][:-1]
    ).cumsum(dim=0)

    return labels, text, offsets, tokenized_list

train_loader = DataLoader(list(zip(X_train, y_train)), batch_size=BATCH_SIZE, shuffle=True, collate_fn=lambda batch: collate_batch(batch, tokenizer, voc))
test_loader = DataLoader(list(zip(X_test, y_test)), batch_size=BATCH_SIZE, shuffle=False, collate_fn=lambda batch: collate_batch(batch, tokenizer, voc))

In [14]:
EPOCHS = 500
EMB_SIZE = 32
CHECKPOINT = './models/embedding_bag_amazon_1000'
USE_PRETRAINED = False  # change to False if you want to retrain your own model

def train_model(train_loader, val_loader):
    model = EmbeddingBagModel(len(voc), EMB_SIZE, num_class)
    
    loss = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters())
    best_acc = 0
    for epoch in range(1, EPOCHS + 1):      
        # training
        model.train()
        total_acc, total_count = 0, 0
        
        for idx, (label, text, offsets, _) in enumerate(train_loader):
            optimizer.zero_grad()
            predited_label = model(text, offsets)
            loss(predited_label, label).backward()
            optimizer.step()
            total_acc += (predited_label.argmax(1) == label).sum().item()
            total_count += label.size(0)

            if (idx + 1) % 500 == 0:
                print('epoch {:3d} | {:5d}/{:5d} batches | accuracy {:8.3f}'.format(
                    epoch, idx + 1, len(train_loader), total_acc / total_count
                ))
                total_acc, total_count = 0, 0       
        
        # evaluation
        model.eval()
        total_acc, total_count = 0, 0

        with torch.no_grad():
            for label, text, offsets, _ in val_loader:
                predited_label = model(text, offsets)
                total_acc += (predited_label.argmax(1) == label).sum().item()
                total_count += label.size(0)

        # print('-' * 59)
        acc = total_acc / total_count
        print('end of epoch {:3d} | valid accuracy {:8.3f} '.format(epoch, acc))
        # print('-' * 59)
        if total_acc/total_count > best_acc:
            best_acc = acc
            print('best_acc', best_acc)
            torch.save(model, CHECKPOINT+'_epoch'+str(epoch)+'.pt')
    return model
        
eb_model = torch.load(CHECKPOINT) if USE_PRETRAINED else train_model(train_loader, test_loader)

end of epoch   1 | valid accuracy    0.473 
best_acc 0.47333333333333333
end of epoch   2 | valid accuracy    0.473 
end of epoch   3 | valid accuracy    0.473 
end of epoch   4 | valid accuracy    0.480 
best_acc 0.48
end of epoch   5 | valid accuracy    0.480 
end of epoch   6 | valid accuracy    0.487 
best_acc 0.4866666666666667
end of epoch   7 | valid accuracy    0.487 
end of epoch   8 | valid accuracy    0.493 
best_acc 0.49333333333333335
end of epoch   9 | valid accuracy    0.500 
best_acc 0.5
end of epoch  10 | valid accuracy    0.507 
best_acc 0.5066666666666667
end of epoch  11 | valid accuracy    0.500 
end of epoch  12 | valid accuracy    0.520 
best_acc 0.52
end of epoch  13 | valid accuracy    0.513 
end of epoch  14 | valid accuracy    0.513 
end of epoch  15 | valid accuracy    0.520 
end of epoch  16 | valid accuracy    0.520 
end of epoch  17 | valid accuracy    0.513 
end of epoch  18 | valid accuracy    0.520 
end of epoch  19 | valid accuracy    0.513 
end of ep

KeyboardInterrupt: 

In [51]:
from torch.nn import functional as F
test_label = 1 
test_line = ('I sort of like this product, its really not my favorite, but it really isnt the best. could be way better.')

test_labels, test_text, test_offsets, _ = collate_batch([(test_line, test_label)])

probs = F.softmax(eb_model(test_text, test_offsets), dim=1).squeeze(0)
print('Prediction probability:', round(probs[test_labels[0]].item(), 4))

Prediction probability: 0.311


In [52]:
probs

tensor([0.6890, 0.3110], grad_fn=<SqueezeBackward1>)

In [53]:
from captum.attr import Lime, LimeBase
from captum._utils.models.linear_model import SkLearnLinearRegression, SkLearnLasso

In [54]:
# remove the batch dimension for the embedding-bag model
def forward_func(text, offsets):
    return eb_model(text.squeeze(0), offsets)

# encode text indices into latent representations & calculate cosine similarity
def exp_embedding_cosine_distance(original_inp, perturbed_inp, _, **kwargs):
    original_emb = eb_model.embedding(original_inp, None)
    perturbed_emb = eb_model.embedding(perturbed_inp, None)
    distance = 1 - F.cosine_similarity(original_emb, perturbed_emb, dim=1)
    return torch.exp(-1 * (distance ** 2) / 2)

# binary vector where each word is selected independently and uniformly at random
def bernoulli_perturb(text, **kwargs):
    probs = torch.ones_like(text) * 0.5
    return torch.bernoulli(probs).long()

# remove absenst token based on the intepretable representation sample
def interp_to_input(interp_sample, original_input, **kwargs):
    return original_input[interp_sample.bool()].view(original_input.size(0), -1)

lasso_lime_base = LimeBase(
    forward_func, 
    interpretable_model=SkLearnLasso(alpha=0.08),
    similarity_func=exp_embedding_cosine_distance,
    perturb_func=bernoulli_perturb,
    perturb_interpretable_space=True,
    from_interp_rep_transform=interp_to_input,
    to_interp_rep_transform=None
)

In [55]:
test_text, test_labels

(tensor([  4,   0,  18,  50,  11,  43,   7,  90,  64,  17,  13,   0,   7,  31,
           6,  64,   0,   3,  63,   2, 108,  44,   0,  87,   2]),
 tensor([1]))

In [58]:
attrs = lasso_lime_base.attribute(
    test_text.unsqueeze(0), # add batch dimension for Captum
    target=test_labels,
    additional_forward_args=(test_offsets,),
    n_samples=16,
    show_progress=True
).squeeze(0)

print('Attribution range:', attrs.min().item(), 'to', attrs.max().item())

Lime Base attribution:   0%|          | 0/16 [00:00<?, ?it/s]

Attribution range: -0.8828542232513428 to 1.0538634061813354


In [59]:
def show_text_attr(attrs):
    rgb = lambda x: '255,0,0' if x < 0 else '0,255,0'
    alpha = lambda x: abs(x) ** 0.5
    token_marks = [
        f'<mark style="background-color:rgba({rgb(attr)},{alpha(attr)})">{token}</mark>'
        for token, attr in zip(tokenizer(test_line), attrs.tolist())
    ]
    
    display(HTML('<p>' + ' '.join(token_marks) + '</p>'))

In [60]:
# positive
attrs = lasso_lime_base.attribute(
    test_text.unsqueeze(0), # add batch dimension for Captum
    target=test_labels,
    additional_forward_args=(test_offsets,),
    n_samples=5000,
    show_progress=True
).squeeze(0)

print('Attribution range:', attrs.min().item(), 'to', attrs.max().item())

Lime Base attribution:   0%|          | 0/5000 [00:00<?, ?it/s]

Attribution range: -1.5195974111557007 to 1.7107371091842651


In [61]:
# positive
show_text_attr(attrs)